name: Deploy

on:
  workflow_dispatch:
#  push:
#    branches:
#      - main

jobs:
  tests:
    uses: ./.github/workflows/tests.yml

  deploy:
    needs: tests
    uses: ./.github/workflows/run-deployment.yml
    secrets: inherit
