name: Deploy

on:
  push:
    branches:
      - main

jobs:
  run-tests:
    uses: ./.github/workflows/tests.yml

  deploy:
    needs: run-tests
    uses: ./.github/workflows/run-deployment.yml
    secrets: inherit
