name: Create and Test Project

on:
  workflow_dispatch:
  push:

jobs:
  test-e2e:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Set up webserver
        run: |
          ./run prepare:repo
          ./run prepare:container
          touch wrapper-mingle/database/database.sqlite
          docker compose run --rm webapp php artisan migrate --seed
          ./run dev:server

      - name: Create E2E and Test Project
        run: |
          npm ci
          npx playwright install --with-deps
          # Wait for the webserver to be ready
          curl http://localhost:8080
          npx wait-on http://localhost:8080 -t 15s
          npm run test

      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
