name: Create and Test Project

on:
  workflow_dispatch:
  push:
#    branches: [ "main" ]
#  pull_request:
#    branches: [ "main" ]


jobs:

  test-project-e2e:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up environment
        run: |
          echo "SHA_SHORT=$(git rev-parse --short $GITHUB_SHA)" >> $GITHUB_ENV
          cd wrapper-mingle ; composer install
          nohup php artisan serve --host=0.0.0.0 --port=8080 > /dev/null &
          cd ..
          curl http://localhost:8080

      - name: Create and Test Project
        if: ${{ false }}
        run: |
          cd playwright
          npm ci
          npx playwright install --with-deps
          echo "Installation done".
          npx playwright test

      - uses: actions/upload-artifact@v4
        if: ${{ false }}
        with:
          name: playwright-report
          path: playwright/playwright-report/
          retention-days: 30
