name: Run tests

on:
  workflow_call:
  push:
    branches:
      - '**'        # This matches any branch
      - '!main'     # This excludes main branch

jobs:
  pest-tests:
    uses: ./.github/workflows/run-pest-tests.yml

  e2e-tests:
    needs: pest-tests
    uses: ./.github/workflows/run-e2e-tests.yml
